name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-with-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: segformer_playground:latest
          load: true
          cache-to: type=inline

      - name: Run pytest
        run: docker run -v ${{ github.workspace }}:/home/segformer_playground segformer_playground pytest
